version: '3'
services:
  django:
    build: ./Django-Boilerplate
    container_name: django
  mern-backend:
    build: ./MERN-Boilerplate/backend
    container_name: mern-backend
  mern-frontend:
    build: ./MERN-Boilerplate/frontend
    container_name: mern-frontend
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
      - mern-backend
      - mern-frontend
